kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    defaultDashboardsTimezone: Asia/Tokyo

    admin:
      existingSecret: grafana-admin-user

    inMemory:
      enabled: true
      sizeLimit: 256Mi

    grafana.ini:
      server:
        root_url: https://grafana.lachlan.io
  
  prometheus:
    prometheusSpec:
      retention: 10d
      retentionSize: 10GB

      resources:
        # limits:
        #   cpu: 1
        #   memory: 1Gi
        requests:
          cpu: 500m
          memory: 500Mi
      
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 30Gi

  cleanPrometheusOperatorObjectNames: true
