apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-user
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: admin-user
      remoteRef:
        key: /monitoring/grafana-admin-user
        property: username
    - secretKey: admin-password
      remoteRef:
        key: /monitoring/grafana-admin-user
        property: password
