---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 24h
  url: https://bjw-s.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: paperless
        namespace: paperless
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.15.1
            env:
              PAPERLESS_URL: https://paperless.lachlan.io
              PAPERLESS_ADMIN_USER: admin
              PAPERLESS_OCR_LANGUAGE: eng+jpn
              PAPERLESS_TIME_ZONE: Asia/Tokyo
              PAPERLESS_OCR_LANGUAGES: jpn
            envFrom:
              - secret: paperless-secrets
          redis:
            image:
              repository: redis
              tag: 7.4.2
    service:
      main:
        controller: main
        primary: true
        ports:
          http:
            port: 8000
            protocol: HTTP
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 50m
        hosts:
          - host: paperless.lachlan.io
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
    persistence:
      data:
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          main:
            main:
              - path: /usr/src/paperless/data
                subPath: data
              - path: /usr/src/paperless/media
                subPath: media
