---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_ADMIN_PASSWORD: AgC972I1KPfNrkAZgsgZIveednY/GuFsV70+jtC/Wb0jmKsInKKyNU6DL2VgqqdiX0lWr5sv5aXJWOdGXDtAXUtMPlbxWPtBAGfw7Wf18iH70eJTRRY3oLVMFdMgcjCUhlWWdO8gPqFhVjxLjn/W3HF3OcTt7WxafMGr1vSY8Dp6FT2hdyPodG8v+yolzLmWiIxZHZi2PeFy7RxQ/3IK+12A5HioubnrvySxBTGY/U41fyulTNzDKR5VSPH4yGcJ7lAWphuSNguFsnGsRwSBjD3ehqbJTeGg2u0WKbPBlC9cMpDYsNeazaYF3i/g9P/ruZ7zQojF740B0+uPh8YRoyYdpEI5jX+WBqBYxNRz5i8TsKL/kaw1Uh2glhy17Bwg83OcSdzNRLa4nTK/Klb2LMobWyzOVw7Gs9qCSKJJQDnn6AyZ85Mwo2GyfbB9+fRg8B5BtbaSCtMAXyPi6Ai4fap3KPv78UpiT/s9n/7pRmwwQuooRp2jfDJoQEEocPyZdVG6ToCxwTPlhOjdE9yXleQqfIfz8HZpmGMK8SCPbSi5W9hsMdMrU4vCUmx/NiaiW/vDRFQPqf3W2Y/MhZa6J5z55Kkhwi4Aelo9OisbE7VgJS5NMPgZ4pLWEb5TrNu2rxZAEVc5MVanrDaUUALUvVpBGRlRBYHNznyqQasUCteb1htVYmEcAc+BeglxaO1HCOTZwfx2O/lC4ofIYeSLVc/wwQpoCv9vy5Fg7wdq5AEPzw==
    PAPERLESS_SECRET_KEY: AgAf4V33tPQ5HG9JdvKsoULkkbNxU9zIh4uTGqvCLRnzlpB8508W1gvTGKoEWQhI87pkmWSa+Rgkc/IN1ePGdLFzk6hGeZPulICjSu59UleWi64Z2W753znyYIqqxgGXa2bWPuv/Wfhb3SXjSf/0vaXdraMo577hzEV5RAxl1wh6zNFxAg+pBS3YZ3YmKATLdfsZOGkgBDiFtwySgc+eL42jttTRu8p7SG7E0y5M0CsPcBJ/Kf1UmPZJ3fkkVJahXbllctBQQc49ghgZtMF/SWXSNia1kiEIC05AgolnX++GR4ZFbf7XsSNdcSSgPJebioYwo6EOjcjV+8yhJj2bKCzYKzGksg2sxqwz1X4o/wuH9Y9iGaIGsu641B0YPC3/6KAPFN0N8Qa3W6zIBcJiTxel86VLkc2/0jkcodRk/CaY33TozKFFWUz5W4k9n+tXBPvIiEP7DbWYVYddAMCFgm+1OTqYvzGvzi41Xs7lxELKd+2IinaM4+3jqBjhz6F/GCKWhw0SW3MogKh/wrSunUry//65vklQeB0hWXbCTMIQpRjCN2KWXVbkDEUqDKQqLOU1AGY2GPILqR1K9vvxQAaPT1prx7nxSVWdFgYf+kJMzv3KJ18dxj6Bb7DW2o1BWoJudtvDouHqB4BV/usuuivA1mi2p7mq2icbtgN3XgOppjtIqlSVlM7lbiEyiT2FDHF41eqfBq/gnfvhm4KnqrZaopLvJgVWawAXdUX4L6/SOQ==
  template:
    metadata:
      name: paperless-secrets
      namespace: paperless
