---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_ADMIN_PASSWORD: AgB6B3hB1mnc+4Uum/zaiBQREXhDjMorfGtMAasaS48+pYZfOV8OmHFjHQ8Y+0RUoxMyVRkSVuMiy66MmL1c14iWdaotOoJfVNxlWowkkpeTdZQ3Ven1PKLnIILERXvpqlTibXQMGOQ8RbJnEJz/gRI79jY6gaFXiLh7zMxh8xrKUV5inA+IuNoJauNES65Vm88naqpShUS8DqSKQ4jJjUU4/V5VJvmr46n0JLqoIF7hwEYrmayMArQzlu6ECQ5kJPEkMgzNvusDvaiRcSlmHFAOgH/N7CUEWuPsR76n6NKIhscwFY9Yi8uCPvdyRWgM6aHo5FIFDP2bsroC7vsAnRauo7nlfgNxjvepqA2zZdm65+PHgkhD+DoErGqqAm5IM49qUsRCAGCQ+8dZCC2DW//GHJOrY46kXwWvO4zgd8pNQelZJP34/ex1qf2IbD+SlrbESaFgmXzevHv6+alD+o8GtMkNQSlLn+AUj42cG7pXZp+HowEjjhHfIEoBcsFlREvc16lxRG3NnpCsJ67JvMex/9GXf/qk76xdXJgkVHZ2EexQxel9as2gI8ZVsqGLAJTuk9g6lU981OKuIL2rkMR354M5JQKdCPldSBswFE2EHxfLQc9Mj3X6K9IIdzHBh+5Bqve9mPgyayntKJrpmQllnhmRsb1MM+SSK5oLl+cKe0Z8UwN/UbM73TNnc9b6lUWTs+sJqMDZiF5HwpndjuhHUWxICHp966Q=
    PAPERLESS_SECRET_KEY: AgAMPStgVzBqES6jmxuVnrplUKvi0gnpCUwnE0ymaJU5pLk+MGAl3yUfxjMCITB2nQyUELXUuscq3YLoj0C4IOxuNJMOX9OdT13DY2TAUuRwNGYA8Dcjie6S9JFd2dEZ2eIea8q08e4I1w1LCetDerx1aNEgzHu/QAkuqVJPh7sZjNe4UQYuoMzZags1VopHZTXxxbtSXKeZytQOzpaaGBXYUUIcdPZ2F/oCcgDC9/RlVcF5mWevnpBPpcXA0bjV9wPFI0WiR47hkoo/nssB0OdynFb91BYoXF615nHY/WhCUCufdqYAOThtX3JyKtiHKfGzOylvBgOHoukYZhg+yLkGcYAmqDRFdEUcn4V4t1+oQQF9PeDRjxakiv+0voXtrXubQrceVIpqNoTWs9EgZfPQ5vUPWR1ADyx68LwvpS6vJityqp5k82EY83nP1TCN3MEgRjWJGB4caE+mO4d3RoD5+sqNsQuYAQhZ+nQhEihHDksnffGy/+xw8x2VUoLNZo8r2hzkcqilB+bR7xCu/PBWX7ty5xuaqkDBV3oM4R9oDrzZ1IueQrMXuFGAGT7lb3etzfPWcy9lYnYTJ0GzHztUZBDTUqmquN3A9mCYoe9MvbJ4Fzt5Fdsdx/ZWbPp/NrWDFs8sThUbyqHrGQm+WPxXm5ffyYoInK1FO4xIDziM3dSG8Z1k5D8CqkBpuQXU0rTUr+SYJ1gZ0+Usmy/susemN8t8wP8wXFQ=
  template:
    metadata:
      name: paperless-secrets
      namespace: paperless
