---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 24h
  url: https://bjw-s.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: adguard-home
        namespace: adguard-home
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: adguard/adguardhome
              tag: v0.107.57
            env:
              TZ: Asia/Tokyo
    service:
      main:
        controller: main
        primary: true
        ports:
          http:
            port: 3000
            protocol: HTTP
      dns:
        controller: main
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.86.225
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: adguard.lachlan.io
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
    persistence:
      conf:
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /opt/adguardhome/conf
            subPath: conf
