hajimari:
  env:
    TZ: Asia/Tokyo
  
  hajimari:
    namespaceSelector:
      any: true
    
    name: you
    
    lightTheme: lbm
    darkTheme: lbm
    customThemes:
      - name: lbm
        backgroundColor: "#1a202c"
        primaryColor: "#ffffff"
        accentColor: "#9f7aea"
    
    showAppGroups: false

    globalBookmarks:
      - group: Development
        bookmarks:
          - name: GitHub
            url: https://github.com
          - name: Stack Overflow
            url: https://stackoverflow.com
          - name: Artifact Hub
            url: https://artifacthub.io
      - group: Security
        bookmarks:
          - name: huntr
            url: https://huntr.dev
          - name: CTFtime
            url: https://ctftime.org
          - name: Hack The Box
            url: https://www.hackthebox.com
      - group: Media
        bookmarks:
          - name: YouTube
            url: https://www.youtube.com
          - name: Netflix
            url: https://www.netflix.com
          - name: Prime Video
            url: https://www.amazon.co.jp/Amazon-Video/b?ie=UTF8&node=2351649051
  
  persistence:
    data:
      enabled: false
