---
apiVersion: v1
kind: Namespace
metadata:
  name: csi-driver-nfs
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: csi-driver-nfs
      interval: 12h
  values:
    controller:
      runOnControlPlane: true
    storageClass:
      create: true
      name: nfs-csi
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      parameters:
        server: 192.168.86.205
        share: /volume1/nfs
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      mountOptions:
        - nfsvers=4.1
