---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 24h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: kube-system
      interval: 12h
  values:
    fullnameOverride: sealed-secrets-controller
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
