apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
