---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  interval: 24h
  url: https://bjw-s.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: actualbudget
        namespace: actualbudget
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: actualbudget/actual-server
              tag: 25.3.1-alpine
    service:
      main:
        controller: main
        ports:
          http:
            port: 5006
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: budget.lachlan.io
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      data:
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /data
